# Generated by Django 3.1.1 on 2020-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_description', models.CharField(max_length=1000)),
                ('expense_category', models.CharField(max_length=256)),
                ('expense_date', models.DateField(default='none', max_length=500)),
            ],
        ),
    ]
