# Generated by Django 3.1.1 on 2020-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='expense_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='expense_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='expense_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='expense_description',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='amount',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
